#!/usr/bin/env node
// Write scripts/story-keys.txt — one line per story: its FULL-NAME id and the
// Jira key that holds it.
//
// It exists because nothing committed said which key a story has, and the
// planner needed to know. backlog.txt speaks short prefixes (IDN-8-API) and no
// keys; BACKLOG.md is generated from it and speaks the same. So a plan citing
// "IDENTITY-8-API (CRM-nn)" was guessing the number, usually by counting — and
// it got the same story wrong twice in two days, naming CRM-52, which is a
// different story in the same sprint. verify-plan caught both, by asking Jira.
//
// Catching it twice is a working check and a broken process. A guess that a
// check corrects is still a guess, and it costs a round trip through a human
// every time. This gives the planner the answer to read.
//
// The file is committed, and verify-plan checks it against Jira on every run:
// a map nobody verifies is a second source of truth, which is the defect it
// was written to remove rather than move.
//
//   node scripts/story-keys.mjs          refresh it from Jira
//   node scripts/story-keys.mjs --check  exit 1 if it disagrees with Jira

import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { readBacklog } from './lib/backlog.mjs'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = join(HERE, '..')
const OUT = join(HERE, 'story-keys.txt')
const CHECK = process.argv.includes('--check')

const { ids, ID_RE } = readBacklog(HERE)

// The same credentials read the same way verify-plan reads them: the token is
// a YAML block scalar, so its value sits behind an indicator.
function fromJira() {
  const secrets = join(ROOT, '.squad/secrets.yaml')
  if (!existsSync(secrets)) return null
  const text = readFileSync(secrets, 'utf8')
  const token = text.match(/token:\s*(?:[|>][-+\d]*)?\s*([A-Za-z0-9_=\-.]{20,})/)?.[1]
  const host = text.match(/host:\s*(\S+)/)?.[1]
  const email = text.match(/email:\s*(\S+)/)?.[1]
  if (!token || !host || !email) return null

  const auth = Buffer.from(`${email}:${token}`).toString('base64')
  const jql = encodeURIComponent('project = CRM ORDER BY key ASC')

  // Paged, and it has to be. `maxResults=200` was asked for and Jira answered
  // 100 — the cap is the server's, and it does not say it applied one. So this
  // file silently held the first hundred issues and nothing after them: every
  // service-levels, notifications, portal and reports story was simply absent,
  // and a plan citing one had nowhere to read its key.
  //
  // `--check` did not catch it, and could not: it fetched the same truncated
  // page and compared the file to it, so both sides were missing the same 53
  // stories and agreed. A check that reads one source proves only that the
  // source agrees with itself.
  const map = new Map()
  let token_ = null
  for (;;) {
    const url = `https://${host}/rest/api/3/search/jql?jql=${jql}&fields=summary&maxResults=100`
      + (token_ ? `&nextPageToken=${encodeURIComponent(token_)}` : '')
    const page = JSON.parse(execFileSync('curl', ['-s', '--max-time', '30',
      '-H', `Authorization: Basic ${auth}`, '-H', 'Accept: application/json', url,
    ], { encoding: 'utf8' }))
    for (const issue of page.issues ?? []) {
      const id = issue.fields.summary.match(ID_RE)?.[0]
      if (id) map.set(id, issue.key)
    }
    if (!page.nextPageToken) break
    token_ = page.nextPageToken
  }
  return map.size ? map : null
}

const live = fromJira()
if (!live) {
  console.error('story-keys: Jira was not reachable, and this file is only ever written from it')
  process.exit(CHECK ? 0 : 1)   // --check stays silent offline; verify-plan says the same
}

const lines = [...live.entries()]
  .filter(([id]) => ids.has(id))
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([id, key]) => `${id} ${key}`)

// Two independent statements of one number: the backlog says how many stories
// exist, the tracker says how many it returned. They must agree.
//
// Without this the file was short by 53 stories for eight sprints and every
// run said so — "wrote 85 stories" — beside a backlog this repository counts
// as 138 elsewhere. Nobody subtracted. A count printed for a person to check
// is a count nobody checks, so the subtraction happens here (L-65).
if (lines.length !== ids.size) {
  const missing = [...ids].filter((id) => !live.has(id))
  console.error(`story-keys: the backlog has ${ids.size} stories and the tracker answered for ${lines.length}`)
  if (missing.length) console.error(`  not in the tracker: ${missing.slice(0, 10).join(', ')}${missing.length > 10 ? ` (+${missing.length - 10})` : ''}`)
  console.error('  a short answer is usually an unpaged fetch, not a missing story')
  process.exit(1)
}

const header = [
  '# story-keys.txt — which Jira key holds which story. Generated by',
  '# scripts/story-keys.mjs from the tracker; never edited by hand.',
  '#',
  '# Cite a story as FULL-NAME (KEY) and take the key from here. backlog.txt',
  '# has the ids and not the keys, so anything else is counting — which has',
  '# already put the wrong key in two plans.',
  '',
]
const body = header.concat(lines).join('\n') + '\n'

if (CHECK) {
  const on = existsSync(OUT) ? readFileSync(OUT, 'utf8') : ''
  if (on !== body) {
    console.error('story-keys.txt disagrees with Jira — run: node scripts/story-keys.mjs')
    process.exit(1)
  }
  console.log(`story-keys: ${lines.length} stories, and the file agrees with the tracker`)
} else {
  writeFileSync(OUT, body)
  console.log(`story-keys: wrote ${lines.length} stories to scripts/story-keys.txt`)
}
