#!/usr/bin/env node
// Write scripts/story-keys.txt — one line per story: its FULL-NAME id and the
// Jira key that holds it.
//
// It exists because nothing committed said which key a story has, and the
// planner needed to know. backlog.txt speaks short prefixes (IDN-8-API) and no
// keys; BACKLOG.md is generated from it and speaks the same. So a plan citing
// "IDENTITY-8-API (CRM-nn)" was guessing the number, usually by counting — and
// it got the same story wrong twice in two days, naming CRM-52, which is a
// different story in the same sprint. verify-plan caught both, by asking Jira.
//
// Catching it twice is a working check and a broken process. A guess that a
// check corrects is still a guess, and it costs a round trip through a human
// every time. This gives the planner the answer to read.
//
// The file is committed, and verify-plan checks it against Jira on every run:
// a map nobody verifies is a second source of truth, which is the defect it
// was written to remove rather than move.
//
//   node scripts/story-keys.mjs          refresh it from Jira
//   node scripts/story-keys.mjs --check  exit 1 if it disagrees with Jira

import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { readBacklog } from './lib/backlog.mjs'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = join(HERE, '..')
const OUT = join(HERE, 'story-keys.txt')
const CHECK = process.argv.includes('--check')

const { ids, ID_RE } = readBacklog(HERE)

// The same credentials read the same way verify-plan reads them: the token is
// a YAML block scalar, so its value sits behind an indicator.
function fromJira() {
  const secrets = join(ROOT, '.squad/secrets.yaml')
  if (!existsSync(secrets)) return null
  const text = readFileSync(secrets, 'utf8')
  const token = text.match(/token:\s*(?:[|>][-+\d]*)?\s*([A-Za-z0-9_=\-.]{20,})/)?.[1]
  const host = text.match(/host:\s*(\S+)/)?.[1]
  const email = text.match(/email:\s*(\S+)/)?.[1]
  if (!token || !host || !email) return null

  const auth = Buffer.from(`${email}:${token}`).toString('base64')
  const out = execFileSync('curl', ['-s', '--max-time', '30',
    '-H', `Authorization: Basic ${auth}`, '-H', 'Accept: application/json',
    `https://${host}/rest/api/3/search/jql?jql=${encodeURIComponent('project = CRM ORDER BY key ASC')}&fields=summary&maxResults=200`,
  ], { encoding: 'utf8' })

  const map = new Map()
  for (const issue of JSON.parse(out).issues ?? []) {
    const id = issue.fields.summary.match(ID_RE)?.[0]
    if (id) map.set(id, issue.key)
  }
  return map.size ? map : null
}

const live = fromJira()
if (!live) {
  console.error('story-keys: Jira was not reachable, and this file is only ever written from it')
  process.exit(CHECK ? 0 : 1)   // --check stays silent offline; verify-plan says the same
}

const lines = [...live.entries()]
  .filter(([id]) => ids.has(id))
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([id, key]) => `${id} ${key}`)

const header = [
  '# story-keys.txt — which Jira key holds which story. Generated by',
  '# scripts/story-keys.mjs from the tracker; never edited by hand.',
  '#',
  '# Cite a story as FULL-NAME (KEY) and take the key from here. backlog.txt',
  '# has the ids and not the keys, so anything else is counting — which has',
  '# already put the wrong key in two plans.',
  '',
]
const body = header.concat(lines).join('\n') + '\n'

if (CHECK) {
  const on = existsSync(OUT) ? readFileSync(OUT, 'utf8') : ''
  if (on !== body) {
    console.error('story-keys.txt disagrees with Jira — run: node scripts/story-keys.mjs')
    process.exit(1)
  }
  console.log(`story-keys: ${lines.length} stories, and the file agrees with the tracker`)
} else {
  writeFileSync(OUT, body)
  console.log(`story-keys: wrote ${lines.length} stories to scripts/story-keys.txt`)
}
